language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t saarthak08/react-frontend -f DockerPractice/frontend/Dockerfile .

script:
  - docker run -e CI=true saarthak08/react-frontend npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sample-application"
  env: "Sampleapplication-env"
  bucket_name: "elasticbeanstalk-us-east-1-602282513411"
  bucket_path: "sample-application"
  on:
    branch: master
  session_token: $session_token
  access_key_id: $access_key_id 
  secret_access_key: $secret_access_key

