language: generic
sudo: required
services: 
  - docker

branches:
  only:
  - master


before_install:
  - docker build -t saarthak08/react-frontend-test -f Dockerfile.dev .

script:
  - docker run -e CI=true saarthak08/react-frontend-test npm run test -- --coverage
  
after_success:
  - docker build -t saarthak08/react-frontend .


deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "sample-react-frontend"
  env: "Samplereactfrontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-098519501475"
  bucket_path: "sample-application"
  on:
    branch: master
  access_key_id: $access_key_id 
  secret_access_key: $secret_access_key

