language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t saarthak08/react-frontend -f DockerPractice/frontend/Dockerfile.dev .

script:
  - docker run -e CI=true saarthak08/react-frontend npm run test -- --coverage

